import type { Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";
import { Geist, Geist_Mono } from "next/font/google";
import { clerkAppearance } from "@/lib/clerk-appearance";
import { editorPath, signInPath, signUpPath } from "@/lib/auth-routes";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} dark h-full`}
    >
      <body className="min-h-full antialiased">
        <ClerkProvider
          appearance={clerkAppearance}
          signInFallbackRedirectUrl={editorPath}
          signInUrl={signInPath}
          signUpFallbackRedirectUrl={editorPath}
          signUpUrl={signUpPath}
        >
          {children}
        </ClerkProvider>
      </body>
    </html>
  );
}
